name: "My first workflow"

on:
  push:

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: using the echo command 
          run: echo "This is first job"

        - name: list the dir
          run: ls -la

        - name: using the github action
          uses: actions/checkout@v6  

        - name: read the file 
          run: cat README.md

        - name: upload the artifacts 
          uses: actions/upload-artifact@v4
          with:
            name: myartifact
            path: ./README.md 

    second_job:
        needs: first_job
        runs-on: ubuntu-latest
        steps:
        - name: Download the artifacts 
          uses: actions/download-artifact@v5
          with:
            name: myartifact

        - name: uisng the multiline command
          run: |
            echo "This is second job"
            ls -ltra 
            cat README.md
    third_job:
        needs: second_job
        runs-on: ubuntu-latest
        steps: 
        - name: using the github action
          uses: actions/checkout@v6 

        - name: change the permission
          run: chmod 777 sample.sh

        - name: running the shell script 
          run: ./sample.sh  
                      
                  


