name: "My first workflow"

on:
  push:

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: using the echo command 
          run: echo "This is first job"

        - name: list the dir
          run: ls -la

        - name: read the file 
          run: cat README.md

